version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  npm_cache:
    jobs:
      - build
  heroku_deploy:
    jobs:
      - deploy
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: |
            echo "The command above installs Heroku, the command below deploys. What you do inbetween is up to you!"
      - heroku/deploy-via-git:
          force: true
          branch: master
