version: 2
jobs:
  build:
    working_directory: /go/src/github.com/guptamohit004/social-connect
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "web/package.json" }}
            - dependencies-

      - run:
          working_directory: web
          command: |
            yarn install
      - save_cache:
          paths:
            - web/node_modules
          key: dependencies-{{ checksum "web/package.json" }}
